// @ts-check

const ratioVersions = require("./docs/ratio/versions.json");
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  "ratio-1.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(ratioVersions),
      className: "version-button",
    },
    {
      type: "html",
      value: versionCrumb("v1.0.0"),
    },
    {
      type: "category",
      label: "Ratio",
      link: {
        type: "generated-index",
        title: "Ratio API (Latest)",
        description: "The latest version of the Ratio API",
        slug: "/ratio-api",
      },
      items: require("./docs/ratio/sidebar.js"),
    }
  ],
  "ratio-0.0.1": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(ratioVersions),
      className: "version-button",
    },
    {
      type: "html",
      value: versionCrumb("v0.0.1"),
    },
    {
      type: "category",
      label: "Ratio",
      link: {
        type: "generated-index",
        title: "Ratio API (Latest)",
        description: "The latest version of the Ratio API",
        slug: "/ratio-api-0.0.1",
      },
      items: require("./docs/ratio/0.0.1/sidebar.js"),
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

};

module.exports = sidebars;
